/**
 * Static Command Code model metadata.
 *
 * AUTO-GENERATED by scripts/sync-catalog.mjs from command-code@1.36.0
 * (models.md). Do not edit manually — run `node scripts/sync-catalog.mjs`
 * after CLI updates to refresh.
 */

export type CommandCodeInputType = "text" | "image";
export type CommandCodeReasoningEffort =
  | "minimal"
  | "low"
  | "medium"
  | "high"
  | "xhigh"
  | "max";

export const MODEL_INPUT_MODALITIES: Readonly<
  Record<string, readonly CommandCodeInputType[]>
> = {
  "deepseek/deepseek-v4-flash-vision-exp": ["text", "image"],
  "moonshotai/Kimi-K2.7-Code": ["text", "image"],
  "moonshotai/Kimi-K2.7-Code-Highspeed": ["text", "image"],
  "moonshotai/Kimi-K2.6": ["text", "image"],
  "moonshotai/Kimi-K2.5": ["text", "image"],
  "MiniMaxAI/MiniMax-M3": ["text", "image"],
  "minimax/minimax-m3-free": ["text", "image"],
  "Qwen/Qwen3.8-27B": ["text", "image"],
  "stepfun/Step-3.7-Flash": ["text", "image"],
  "thinkingmachines/inkling": ["text", "image"],
  "claude-sonnet-5": ["text", "image"],
  "claude-sonnet-4-6": ["text", "image"],
  "claude-fable-5": ["text", "image"],
  "claude-opus-5": ["text", "image"],
  "claude-opus-4-8": ["text", "image"],
  "claude-opus-4-7": ["text", "image"],
  "claude-haiku-4-5-20251001": ["text", "image"],
};

export const MODEL_REASONING: Readonly<Record<string, true>> = {
  "MiniMaxAI/MiniMax-M3": true,
  "Qwen/Qwen3.8-27B": true,
  "Qwen/Qwen3.8-Flash": true,
  "Qwen/Qwen3.8-Max": true,
  "claude-fable-5": true,
  "claude-opus-4-7": true,
  "claude-opus-4-8": true,
  "claude-opus-5": true,
  "claude-sonnet-4-6": true,
  "claude-sonnet-5": true,
  "deepseek/deepseek-v4-flash": true,
  "deepseek/deepseek-v4-flash-vision-exp": true,
  "deepseek/deepseek-v4-pro": true,
  "google/gemini-3.1-flash-lite": true,
  "google/gemini-3.5-flash": true,
  "google/gemini-3.5-flash-lite": true,
  "google/gemini-3.6-flash": true,
  "google/gemini-3.7-flash": true,
  "gpt-5.3-codex": true,
  "gpt-5.4": true,
  "gpt-5.4-mini": true,
  "gpt-5.5": true,
  "gpt-5.6-luna": true,
  "gpt-5.6-sol": true,
  "gpt-5.6-terra": true,
  "moonshotai/Kimi-K2.5": true,
  "moonshotai/Kimi-K2.6": true,
  "nvidia/nemotron-3-ultra-550b-a55b": true,
  "sakana/fugu-ultra": true,
  "stepfun/Step-3.5-Flash": true,
  "tencent/hy3-paid": true,
  "xai/grok-4.5": true,
  "xai/grok-4.6": true,
  "xiaomi/mimo-v2.5": true,
  "z-ai/glm-5.3-flash": true,
  "zai-org/GLM-5.2": true,
  "zai-org/GLM-5.3": true,
};

export const MODEL_EFFORTS: Readonly<
  Record<string, readonly CommandCodeReasoningEffort[]>
> = {
  "deepseek/deepseek-v4-pro": ["high", "max"],
  "deepseek/deepseek-v4-flash": ["high", "max"],
  "deepseek/deepseek-v4-flash-vision-exp": ["high", "max"],
  "z-ai/glm-5.3-flash": ["low", "high", "max"],
  "zai-org/GLM-5.3": ["low", "high", "max"],
  "zai-org/GLM-5.2": ["high", "max"],
  "Qwen/Qwen3.8-Max": ["low", "medium", "xhigh"],
  "Qwen/Qwen3.8-27B": ["low", "medium", "xhigh"],
  "Qwen/Qwen3.8-Flash": ["low", "medium", "xhigh"],
  "claude-sonnet-5": ["low", "medium", "high", "xhigh", "max"],
  "claude-sonnet-4-6": ["low", "medium", "high", "xhigh", "max"],
  "claude-fable-5": ["low", "medium", "high", "xhigh", "max"],
  "claude-opus-5": ["low", "medium", "high", "xhigh", "max"],
  "claude-opus-4-8": ["low", "medium", "high", "xhigh", "max"],
  "claude-opus-4-7": ["low", "medium", "high", "xhigh", "max"],
  "gpt-5.6-sol": ["low", "medium", "high", "xhigh", "max"],
  "gpt-5.6-terra": ["low", "medium", "high", "xhigh", "max"],
  "gpt-5.6-luna": ["low", "medium", "high", "xhigh", "max"],
  "gpt-5.5": ["low", "medium", "high", "xhigh"],
  "gpt-5.4": ["low", "medium", "high", "xhigh"],
  "gpt-5.3-codex": ["low", "medium", "high", "xhigh"],
  "gpt-5.4-mini": ["low", "medium", "high"],
  "google/gemini-3.7-flash": ["low", "medium", "high"],
  "google/gemini-3.6-flash": ["low", "medium", "high"],
  "google/gemini-3.5-flash": ["low", "medium", "high"],
  "google/gemini-3.5-flash-lite": ["low", "medium", "high"],
  "google/gemini-3.1-flash-lite": ["low", "medium", "high"],
  "sakana/fugu-ultra": ["high", "xhigh"],
  "xai/grok-4.5": ["low", "medium", "high"],
  "xai/grok-4.6": ["low", "medium", "high", "xhigh"],
};

export const MODEL_MAX_OUTPUT_TOKENS: Readonly<Record<string, number>> = {
  "poolside/laguna-s-2.1-free": 32768,
  "Qwen/Qwen3.8-27B": 32768,
  "stealth/ox-alpha": 131072,
};

/**
 * Known context windows (tokens) from models.md. Used as a static fallback
 * when live discovery is unavailable or the id is not in the live catalog
 * yet (resolveDynamicModel path).
 */
export const MODEL_CONTEXT_WINDOWS: Readonly<Record<string, number>> = {
  "deepseek/deepseek-v4-pro": 1000000,
  "deepseek/deepseek-v4-flash": 1000000,
  "deepseek/deepseek-v4-flash-vision-exp": 1000000,
  "moonshotai/Kimi-K3": 1000000,
  "moonshotai/Kimi-K2.7-Code": 256000,
  "moonshotai/Kimi-K2.7-Code-Highspeed": 262000,
  "moonshotai/Kimi-K2.6": 256000,
  "moonshotai/Kimi-K2.5": 256000,
  "z-ai/glm-5.3-flash": 1050000,
  "zai-org/GLM-5.3": 1000000,
  "zai-org/GLM-5.2": 1000000,
  "zai-org/GLM-5.2-Fast": 1000000,
  "zai-org/GLM-5": 200000,
  "MiniMaxAI/MiniMax-M3": 1000000,
  "minimax/minimax-m3-free": 1000000,
  "minimax/minimax-m2.7-free": 197000,
  "MiniMaxAI/MiniMax-M2.5": 200000,
  "xiaomi/mimo-v2.5-pro": 1000000,
  "xiaomi/mimo-v2.5": 1000000,
  "Qwen/Qwen3.8-Max": 1000000,
  "Qwen/Qwen3.8-27B": 262000,
  "Qwen/Qwen3.8-Flash": 1000000,
  "Qwen/Qwen3.7-Max": 1000000,
  "Qwen/Qwen3.7-Plus": 1000000,
  "Qwen/Qwen3.7-Flash": 1000000,
  "stepfun/Step-3.7-Flash": 256000,
  "stepfun/Step-3.5-Flash": 1000000,
  "tencent/hy3-paid": 262000,
  "nvidia/nemotron-3-ultra-550b-a55b": 1000000,
  "thinkingmachines/inkling": 256000,
  "thinkingmachines/inkling-small": 1000000,
  "poolside/laguna-s-2.1-free": 256000,
  "claude-sonnet-5": 1000000,
  "claude-sonnet-4-6": 1000000,
  "claude-fable-5": 1000000,
  "claude-opus-5": 1000000,
  "claude-opus-4-8": 1000000,
  "claude-opus-4-7": 1000000,
  "claude-haiku-4-5-20251001": 200000,
  "gpt-5.6-sol": 1050000,
  "gpt-5.6-terra": 1050000,
  "gpt-5.6-luna": 1050000,
  "gpt-5.5": 400000,
  "gpt-5.4": 400000,
  "gpt-5.3-codex": 400000,
  "gpt-5.4-mini": 400000,
  "google/gemini-3.7-flash": 1050000,
  "google/gemini-3.6-flash": 1000000,
  "google/gemini-3.5-flash": 1000000,
  "google/gemini-3.5-flash-lite": 1000000,
  "google/gemini-3.1-flash-lite": 1000000,
  "sakana/fugu-ultra": 1000000,
  "meta/muse-spark-1.1": 1050000,
  "meta/muse-spark-1.2": 1050000,
  "meta/muse-spark-1.2-contributor": 1050000,
  "xai/grok-4.5": 500000,
  "xai/grok-4.6": 500000,
};
